# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'ShoppingList' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ShoppingList
pod 'Popover'

pod 'FirebaseUI'
pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Google'
pod 'FirebaseUI/Facebook'

pod 'FirebaseUI/Phone'

pod 'Firebase/Core'
pod 'Firebase/Storage'


end
